# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "KashiwaByte"
repo_name: "RAG-VectorDatabase-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 100

publish_readme: True
publish_gitpage: False
publish_wechat: False

# file paths
json_readme_path: './docs/Video-Generation-arxiv-daily.json'



md_readme_path: 'README.md'


keywords:
    "Foundation Video Models":
        filters: ["Foundation AND Video AND Models "]
    "Long Video Generation":
        filters: ["Long AND Video AND Generation "]
    "Long Video Generation":
        filters: ["Efficient AND Video AND Generation "]
    "Controllable Video  Generation":
        filters: ["Controllable AND Video AND Generation "]
    "Human Video  Generation":
        filters: ["Human AND Video AND Generation "]
    "Video Editing":
        filters: [" Video AND Editing "]
    "Video Generation Evaluation":
        filters: ["Evaluation AND Video AND Generation "]
    "RAG":
        filters: ["RAG AND LLM"]


